const $=s=>document.querySelector(s),key=$('#key'),script=$('#script'),results=$('#results');
key.value=localStorage.getItem('pexels_api_key')||'';if(key.value)$('#status').textContent='API key saved on this device.';
$('#save').onclick=()=>{if(!key.value.trim())return $('#status').textContent='Paste your key first.';localStorage.setItem('pexels_api_key',key.value.trim());$('#status').textContent='Saved locally on this device.'};
$('#clear').onclick=()=>{localStorage.removeItem('pexels_api_key');key.value='';$('#status').textContent='Key cleared.'};
script.oninput=()=>$('#words').textContent=(script.value.match(/\S+/g)||[]).length+' words';
function split(t){return t.trim().split(/\n+/).flatMap(x=>x.split(/(?<=[.!?।])\s+/)).map(x=>x.trim()).filter(Boolean)}
function queries(s){let x=s.toLowerCase(),q=[];let add=a=>a.forEach(v=>{if(!q.includes(v))q.push(v)});if(/बस|bus|coach/.test(x))add(['old bus driving on mountain road','vintage bus road journey','bus through barren landscape']);if(/पहाड़|mountain|पर्वत|pass|दर्रा|घाट/.test(x))add(['mountain pass road landscape','barren mountain road','rocky mountain valley road']);if(/रेगिस्तान|desert|बंजर|सूखा|sand/.test(x))add(['barren desert landscape','desert road wide shot','dry rocky desert landscape']);if(/जांच|investig|तफ्तीश|detective|अधिकारी|officer|intelligence|खुफिया/.test(x))add(['intelligence officers investigation office','detective examining documents','investigation room paperwork']);if(/नक्शा|map|मानचित्र/.test(x))add(['hands studying paper map','vintage map investigation desk','map and documents close up']);if(/फोटो|photograph|तस्वीर|picture/.test(x))add(['black and white photographs on desk','investigation photographs close up','old photographs documents desk']);if(/शहर|city|tel aviv|तेल अवीव/.test(x))add(['Tel Aviv city street','old city street documentary','Israeli city street']);if(/रात|night|अंधेरा|dark/.test(x))add(['night street documentary','dark city street','night road headlights']);if(!q.length){let w=s.replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(a=>a.length>3);add([w.slice(0,5).join(' ')+' documentary footage',w.slice(0,4).join(' ')+' landscape footage','realistic '+w.slice(0,4).join(' ')+' scene'])}return q.slice(0,3)}
async function search(q,n){let k=key.value.trim()||localStorage.getItem('pexels_api_key');let u='https://api.pexels.com/v1/videos/search?'+new URLSearchParams({query:q,orientation:'landscape',size:'medium',per_page:Math.min(20,n)});let r=await fetch(u,{headers:{Authorization:k}});if(r.status===401)throw Error('Invalid API key');if(r.status===429)throw Error('Pexels rate limit reached');if(!r.ok)throw Error('Pexels error '+r.status);return r.json()}
function file(v){return (v.video_files||[]).find(f=>+f.width===1920&&+f.height===1080)||null}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(i,s,qs,items){let el=document.createElement('section');el.className='shot';el.innerHTML='<div class="shothead"><div class="num">SHOT '+String(i+1).padStart(2,'0')+'</div><div class="narration">'+esc(s)+'</div><div class="queries">'+qs.map(q=>'<span class="q">'+esc(q)+'</span>').join('')+'</div></div><div class="cards">'+(items.length?items.map(({v,f})=>'<article class="card"><div class="thumb"><img loading="lazy" src="'+esc(v.image)+'"></div><div class="meta"><div>'+esc(v.user?.name||'Pexels creator')+'</div><div class="chips"><span class="chip">1920×1080</span><span class="chip">'+(v.duration||'?')+'s</span><span class="chip">'+(f.fps||'')+' fps</span></div><div class="actions"><a class="watch" href="'+esc(f.link)+'" target="_blank">Watch</a><button class="use" data-link="'+esc(f.link)+'">Use</button></div></div></article>').join(''):'<div class="empty">No exact 1920×1080 landscape result found for this shot.</div>')+'</div>';results.appendChild(el);el.querySelectorAll('.use').forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(b.dataset.link);b.textContent='Copied';setTimeout(()=>b.textContent='Use',900)})}
$('#go').onclick=async()=>{results.innerHTML='';if(!key.value.trim()&&!localStorage.getItem('pexels_api_key'))return $('#status').textContent='Add your Pexels API key first.';let shots=split(script.value);if(!shots.length)return results.innerHTML='<section class="panel empty">Paste your narration first.</section>';let limit=+$('#count').value;$('#progress').classList.remove('hidden');$('#go').disabled=true;try{for(let i=0;i<shots.length;i++){let qs=queries(shots[i]),map=new Map();$('#progress').textContent='Finding footage for shot '+(i+1)+' of '+shots.length+'…';for(let q of qs){let d=await search(q,20);for(let v of d.videos||[]){let f=file(v);if(f&&!map.has(v.id))map.set(v.id,{v,f})}}render(i,shots[i],qs,[...map.values()].slice(0,limit))}$('#progress').textContent='Finished — '+shots.length+' shots.'}catch(e){results.insertAdjacentHTML('afterbegin','<section class="panel error">'+esc(e.message)+'</section>');$('#progress').textContent='Stopped.'}finally{$('#go').disabled=false}};
